import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import NavBar from "./_components/navbar";
import Footer from "./_components/footer";

// TODO:change title and public favicon
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="mx-auto flex min-h-screen w-full max-w-5xl flex-col">
        <NavBar className="" />
        <div className="flex flex-1 flex-col">{children}</div>
        <Footer className="" />
      </body>
    </html>
  );
}
